### ISSUE TITLE
[Bug] "You seem to be offline"

### ISSUE THREAD

**Issue by pylapp** [michaelnisi/podest#42]
_Given I select a podcast to listen and get its description
When I tap the play button
A pop-up alert says I seem to be offline but I'm not_

I tested on cellular connection (4G), and domestic network (WiFi), and I disconnected any VP, blokers or probes on my phone.

Nothing found in the app logs (as described in [that comment](https://github.com/michaelnisi/podest/issues/40#issuecomment-1002724988))

Bellow the pop-up I have.

![IMG_0994](https://user-images.githubusercontent.com/7559007/157208272-f2602cce-c6d8-4f68-b99c-66c18e4e17da.PNG)

**Comment by pylapp** [comment]
**Device description:**
- iPhone 12 Pro
- iOS 15.1.1

**Console.app traces**
[podest_offline-bug.txt](https://github.com/michaelnisi/podest/files/8204701/podest_offline-bug.txt)

**Comment by pylapp** [comment]
@michaelnisi Contact me if you want more details :)

**Comment by michaelnisi** [comment]
Thank you, interesting…

 ![image](https://user-images.githubusercontent.com/108903/157219760-3181081c-7632-4509-b3bf-56f2cd7d5402.png)

I'll look into it.

**Comment by pylapp** [comment]
I failed to reproduce it, today the app works fine. Quite strange, but good news :)

**Comment by pylapp** [comment]
@michaelnisi I met this issue again and am able to share that detail: if I am using WiFi it’s ok  but if I’m using cellular connection, this pop-up occurs.
![BF5519FB-36D2-4E86-91B8-16C32F9256CD](https://user-images.githubusercontent.com/7559007/171282316-b912bd2c-f9da-4db2-a684-a622ee2c1619.jpeg)
![B63E7295-3703-4DF5-9A68-167048B0A038](https://user-images.githubusercontent.com/7559007/171282336-7ddc45e2-d975-4d99-a357-006ef064459a.jpeg)
